### PR TITLE
Added two unit tests: one that checks that (eqb decode(encode(c)) c) …

### PR DESCRIPTION
**Pull request by ric-almeida**
…= true, for some c, and another one that checks the two have the same flags. Currently the first test passes but the second one fails, so this requires investigation.

### CODE REVIEW

**Comment by vzaliva** [comment]
We need to find a way to add the test data to the capability module abstract interface.
I understand why you did this, but we need a cleaner way. Maybe create another module, including the current one and add it there?  See how we did this for `MorelloCapabilityWithStrfcap`

**Comment by ric-almeida** [comment]
Yes, agreed on making the tests cleaner.
With regards to the fact that the flags are coming back changed after encoding and decoding a capability, should I create a standalone Issue for it?

**Comment by ric-almeida** [comment]
I made a start at making the tests cleaner. I looked at `MorelloCapabilityWithStrfcap` like you suggested. That's an OCaml module, so I tried to do the same idea in Coq with a new module type called `TestCapabilities` in the interface `Capabilities.v`, which must be instantiated with the `MorelloCapability` module and the field modules. The instantiation is in `Morello.v` but the capability `cap_1` it contains breaks my build:

```
File "./coq/Morello.v", line 923, characters 6-11:
Error: valid: Not a projection.
```

It seems an issue of projections and records. @vzaliva do you have any idea why this is happening?

**Comment by ric-almeida** [comment]
@vzaliva I made some updates. Hopefully the it's now in a good shape to be merged.

**Comment by vzaliva** [comment]
I've simplified your implementation and implemented the same tests in OCaml.

**Pull request closed without merging**
